name: memory_word
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  translator: ^0.1.7
  flutter_tts: ^4.2.5
  speech_to_text: ^7.5.0
  audioplayers: ^6.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/correct.mp3
    - assets/special.mp3
    - assets/wrong.mp3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21